### ISSUE TITLE
How did leaderboard get those usernames?

### ISSUE THREAD

**Issue by MaxZhou1902** [eggpi/citationhunt#111]
I wonder there is no OAuth in citationhunt, how did leaderboard get those users who add citation through citationhunt?

**Comment by eggpi** [comment]
Whenever someone clicks the green button in the UI, we make note of the corresponding snippet and when the click happened. A script runs every few minutes and re-parses those articles looking for snippets that have disappeared since the click.

If a revision newer than the click causes that snippet to disappear (up until some number of hours), then we consider that revision to have fixed the snippet ([code](https://github.com/eggpi/citationhunt/blob/master/scripts/compute_fixed_snippets.py#L140)). This has known flaws (#70) but works reasonably well in practice.

When a user requests the leaderboard, we join the revision IDs stored in our database with the `revision_userindex` table in the Toolforge replica to get the actual users ([code](https://github.com/eggpi/citationhunt/blob/master/handlers/database.py#L77-L90)).

The main reason for things to have ended up this way is that we already had the detection of fixed snippets even before adding leaderboard anyway, so it felt like a natural extension. This also avoids storing usernames in our database and IMHO provides slightly better user experience as users don't need to learn to authenticate through the tool to be counted in the leaderboard.

Let me know if you'd like more information!
