### ISSUE TITLE
Database Update

### ISSUE THREAD

**Issue by PanwarJayant** [eggpi/citationhunt#191]
Hi guys, 
I came across your tool when going through the best Wiki tools of 2022. I have been trying it for a couple of days now. I wanted to ask if the database update jobs are running successfully. 

Because I have come across cases where the tool provides those wiki snippets which no longer need a 'citation'. In some cases, the citation issue has been resolved and in others, the editors have removed the [citation needed] tag but the tool is still listing those snippets when checking for citation-less snippets.

I would be happy to provide snapshots if you think this should not be the case.

PS: Apologies if GitHub Issues is not the appropriate medium to report a technical issue with the tool but I could not think of any other way!

**Comment by eggpi** [comment]
Hi, thanks for reporting this! And yes, this is the right place :)

Is this for English Wikipedia? Looking at the logs, I see we've failed the database update a few times, so I think I'll need to have a closer look (and also make the logs more informative, I'm not clear on when was the last time we _succeeded_).

Having the IDs of some of those outdated snippets could be helpful, but I should be able to figure this out regardless if you don't have them anymore. The ID should be in the URL: for example, that's the 67adda2d in https://citationhunt.toolforge.org/en?id=67adda2d.

I'm traveling at the moment so unfortunately it might take a couple of weeks to get to this.

**Comment by eggpi** [comment]
I've managed to experiment with this a little bit in the past few days, so here's a couple of notes:

- Indeed, the enwiki [database update job](https://github.com/eggpi/citationhunt/tree/master/scripts) has been failing for a while. This is because we keep bumping into the MySQL connection limit (20 per user) and [eventually give up](https://github.com/eggpi/citationhunt/blob/master/scripts/parse_live.py#L123) after too many retries.
- We do have a class to [retry failed database connections](https://github.com/eggpi/citationhunt/blob/master/chdb.py#L18) but it was only retrying failed queries, not the initial connection itself. 59af7005eb0f90426af7570466e99afdd6a0cf80 should fix that.

I've managed to get a successful run so your example snippets should now be gone, thanks for providing them!

I think there are a couple of things that we could do here:

1. _Easy:_ update the retry logic so it tries for longer, e.g. 10 retries instead of the [current 5](https://github.com/eggpi/citationhunt/blob/master/chdb.py#L29).
1. _Easy, but not sure we should:_ remove the "retry until we give up" logic altogether, and just skip all MySQL exceptions we see. The logic is there for defensive programming, to avoid generating a possibly corrupt database.
1. _Medium:_ ensure we run the enwiki update on a day on its own to minimize interference with other jobs. enwiki is by far the longest job, and takes about 12h. To do this, we'd need to [update the script that generates the job schedule](https://github.com/eggpi/citationhunt/blob/master/k8s/crontab.py).
1. _Medium:_ ask Toolforge to just increase the connection limit for Citation Hunt.
1. _Hard, but possibly the proper solution:_ create a new Toolforge account to run these jobs. That way, we don't need to worry about these jobs competing with the serving app for database connections.

I am testing 1 today, and I think we should do at least 1 and 3. If you're familiar with Python and would like to take a look at 3, I'd be happy to review a pull request. Otherwise I'll get to it eventually!

**Comment by eggpi** [comment]
I think we're having consistent database updates again (every ~4 days) so we can close this.

**Comment by eggpi** [comment]
Hey, sure, here's a couple of pointers.

1. Yes, they'll host it for you. See https://wikitech.wikimedia.org/wiki/Portal:Toolforge for the entry point to the docs.
2. Toolforge has their own Kubernetes cluster where you can run various jobs: https://wikitech.wikimedia.org/wiki/Help:Toolforge/Kubernetes. I don't really know much about what limits are enforced there, though.

You can also use [IRC or their mailing lists](https://en.wikipedia.org/wiki/Wikipedia:Wikimedia_Cloud_Services#Support_and_diagnostics) for questions.

Hope this helps!

**Comment by PanwarJayant** [comment]
Thanks a lot for your help!
