### ISSUE TITLE
Categories in Polish seem to not work

### ISSUE THREAD

**Issue by silviaegt** [eggpi/citationhunt#200]
Dear @eggpi,
As I mentioned in my other ticket, your tool is absolutely loved, so much that organizers of #1Lib1Ref keep coming with questions cuz they want to keep using it!
One participant that uses the Polish version of the tool said that the categories aren't quite working. 
I'm not well versed in Polish, but I did try to search for categories using the most used letters in Polish language (like A) and couldn't quite find many articles... any ideas why?
<img width="880" alt="image" src="https://github.com/eggpi/citationhunt/assets/8223258/57ecce58-cbc9-4d65-b959-a2b97223fde4">

**Comment by eggpi** [comment]
Hmm, there does seem to be something wrong with plwiki, and it's not just the categories. I see only 180 snippets in Polish Citation Hunt, under 94 categories.

There is probable some bug in how Citation Hunt identifies the pages to process, because PetScan tells me we should be starting from [23k](https://petscan.wmflabs.org/?psid=26779793) pages. I'll look into this one too, thanks for reporting!

**Comment by silviaegt** [comment]
I just saw it is working now! Thank you so much!
