### ISSUE TITLE
Make the category filter more visible.

### ISSUE THREAD

**Issue by eggpi** [eggpi/citationhunt#24]
A few ideas:
- Make the border darker
- Change the default text to make it more inviting
- Change the color of the default text
- Move the input box somewhere more centered
- Add the `autofocus` attribute, so we get a blinking cursor

**Comment by owcz** [comment]
I think this is still an issue. It took me finding this thread to realize that category-based refining was already built-in. My recommendation would be to put the category box up top, bold it, increase its font size, add indicator of editable status (e.g., change color background, magnifying glass, long underline), and either randomly pick a category at page load or put "Random" in the category box so that users have some indication that the box (1) controls the items displayed, and (2) is changeable to select other topics.

**Comment by eggpi** [comment]
Very interesting, thanks for the suggestions! Here's a few thoughts:

I think the font size increase is definitely a great idea, and so is the indicator of editable status. Up until 1ee035c74bf3456bceaf65c7436cb0283c656cdd, we would autofocus on the category box on non-mobile browsers, so the user would get a blinking cursor to draw their attention. That may not be enough, but I could try to bring it back somehow (as a gif in the background?).

Changing colors would also be nice, and I think giving the border a brighter color would be a nice start. The one thing I'm not sure about is moving the box to the top: I like to keep the controls near one another.

As for the other suggestions, in general, I think I'd rather start from visual changes that make the box stand out more, than go for behavior changes as well. I think #71 does a good job of making it clear what the box is for, it just doesn't stand out much. Glad to revisit this if I get proven wrong, though.

I'll reopen this and see what I can come up with in a few days. If you're interested in mocking something up, feel free to send a PR or screenshot and I'll be happy to take a look. Thanks again!
