### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by Halibutt** [eggpi/citationhunt#39]
- [x] Lead section policy - there's none, we're working on translating WP:LEAD from enwiki, but it's going to take a couple of weeks (our community is pretty conservative and adopting a WP:MoS might take a lot of time)
- [x] [Translate the interface to Polish](https://github.com/eggpi/citationhunt/pull/35#issuecomment-186463442)
- [x] Page about referencing - [Pomoc:Przypisy](https://pl.wikipedia.org/wiki/Pomoc:Przypisy) works like a charm and is up to date. There's also [one on bibliography as such](https://pl.wikipedia.org/wiki/Wikipedia:Bibliografia) and, obviously, [one on Verifiability](https://pl.wikipedia.org/wiki/Wikipedia:Weryfikowalność). 
- [x] Add Polish configuration
- [x] Prepare a [snippet parser](https://github.com/eggpi/citationhunt/tree/master/snippet_parser)

**Comment by eggpi** [comment]
Awesome, thank you! I'm working on Catalan now but will definitely take Polish next :) There's one more bit of information that might be useful: is there anything like [Category:All articles with unsourced statements](https://en.wikipedia.org/wiki/Category:All_articles_with_unsourced_statements) in the Polish Wikipedia?

I use that [in the config](https://github.com/eggpi/citationhunt/blob/master/config.py#L62,L64) to identify which pages to parse. I'm thinking of moving away from that since it doesn't look like all Wikipedias have such a category, but in the meantime, if the Polish has it, that would make things easier.

**Comment by Halibutt** [comment]
Yup, we do have year and month-based categories, added automagically by our {{fakt}}. Here's the parent category: https://pl.wikipedia.org/wiki/Kategoria:Artyku%C5%82y_wymagaj%C4%85ce_uzupe%C5%82nienia_%C5%BAr%C3%B3de%C5%82

**Comment by eggpi** [comment]
Added some basic configuration in 92d1df90c1c62cd067b5f1cfbbfa6a809fabd00a, this seems to be working fine: https://tools.wmflabs.org/citationhunt/pl.

Before merging this, I'd just like to tinker with the number of categories a bit, and browse around some of the snippets we're generating to see if there are any templates that might be worth implementing in snippet_parser.

**Comment by eggpi** [comment]
I'm seeing way less broken snippets than I expected. It's probably fine to merge this and work incrementally on them later if more come up :)
