### ISSUE TITLE
Complete project description page at translatewiki.net

### ISSUE THREAD

**Issue by Nikerabbit** [eggpi/citationhunt#53]
https://translatewiki.net/w/i.php?title=Translating:CitationHunt&action=edit&redlink=1 is missing. You can find examples at https://translatewiki.net/wiki/Group_descriptions

Originally reported at https://translatewiki.net/wiki/Thread:Support/Translating:CitationHunt

**Comment by eggpi** [comment]
Hey, thanks for pointing that out! It seems I don't have permission to create that page, though. Can you grant me permission or should I go ask somewhere?

I just created a TranslateWiki account, since (as far as I remember) I didn't have one; I'm User:Surlycyborg. It seems I don't even have the permission to create my user page for some reason.

**Comment by Nikerabbit** [comment]
I approved your account. Let me know if there are more issues.

**Comment by eggpi** [comment]
Done, thank you!
