### ISSUE TITLE
Allow translation of tool title

### ISSUE THREAD

**Issue by jhsoby** [eggpi/citationhunt#59]
Hi eggpi, would it be possible to make the name of the tool translatable? We would like to have the name translated in Norwegian, but it's not currently possible.

**Comment by eggpi** [comment]
Sure, I'm totally fine with that.

@Sadads - I wonder if you'd have any concerns about this (e.g., whether it would make it significantly harder to prepare promotional material for #1Lib1Ref with the localized tool names)? I guess probably not but I figure it's worth giving you a heads-up.

**Comment by Sadads** [comment]
I have no object for this: I think it gives the campaigns (and other applications of the tool more room to grow, in terms of how they are used (and allows for greater localization of the conversation: #1lib1ref is staying #1lib1ref for the most part, to make sure its viral: but otherwise, no particular concern.

**Comment by eggpi** [comment]
Cool! @jhsoby - I'll be busy with #55 in the next couple of weeks, but I'll get to this eventually. If you want to give it a try, feel free to send me a pull request (and ask whatever questions you might have), and we can get it done sooner :)

**Comment by jhsoby** [comment]
Ok, cool! :-)

**Comment by eggpi** [comment]
Fixed by #60, thanks @jhsoby!
