### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by tommorris** [eggpi/citationhunt#72]
It'd be very useful if there were clear keyboard shortcuts allowing users to choose the 'I got this!' and 'Next!' buttons using the keyboard rather than mouse. You can use the tab key but it isn't as efficient as if there were a clear keyboard shortcut ('n' for next, 'g' for got this perhaps).

**Comment by eggpi** [comment]
Yes, that would be very nice to have!  'n' and 'g' sound reasonable for English, but I'm not sure how that would work for other languages. I guess it would make sense to make the shortcuts translatable, and it would likely be good to have [tooltips](https://ux.stackexchange.com/questions/84709) for discoverability as well.

Let me know if you're interested in working on this, and obviously I'll be happy to help and answer questions. Otherwise, I think I can work something out in the next few days.

**Comment by eggpi** [comment]
I think I'll wait until the weekend to deploy this, just for extra caution - we're getting quite a bit more traffic than normal due to #1Lib1Ref. But 1ee035c adds the 'n' and 'g' shortcuts, and it should hopefully behave sensibly for all keyboard layouts.

(cc @Sadads for visibility, since this is actually very handy!)

**Comment by tommorris** [comment]
This is really great. Thank you @eggpi. I've been testing it today and am definitely going to use Citation Hunt more to reference Wikipedia.

**Comment by Sadads** [comment]
Awesome! You do amazing stuff @eggpi!

Cheers,

Alex
