### ISSUE TITLE
Russian version (2)

### ISSUE THREAD

**Issue by kaganer** [eggpi/citationhunt#85]
Russian translation in translatewiki.net was updated. Please import this again.

**Comment by eggpi** [comment]
The translatewiki people import the strings every few days, it should arrive soon. I don't really have much control over it, I just give them commit access to the repository.

After that, I usually update the server on weekends, since there's less traffic. So the update is coming, in one or two weeks (depending on how many translations get updated in between) :)

**Comment by kaganer** [comment]
Ok, thanks.
