### ISSUE TITLE
The scrollbar hides the article count in the category search box.

### ISSUE THREAD

**Issue by kaganer** [eggpi/citationhunt#86]
In the dropdown list for topics found, vertical scrollbar overrides caption for article numbers. See attachments for English and Russian versions:

![image](https://cloud.githubusercontent.com/assets/25355049/23133426/0b0b259c-f7a2-11e6-92fe-d8406da8b709.png)

![image](https://cloud.githubusercontent.com/assets/25355049/23133383/e44a5fd6-f7a1-11e6-8502-ff3292bad21e.png)

**Comment by eggpi** [comment]
Yeah, that bothers me a bit. We could add some right-padding to that element so its text is not under the scrollbar, but it's not obvious how much padding to add, since the width of the scrollbar depends on the operating system. 

I think there should be some ways to find out what that width is in Javascript though, and we might even have some control over it with CSS. I'll need to investigate this.

I'm also open to other ideas if you have any, of course.

**Comment by kaganer** [comment]
In my experience in standalone software, this should be some "display property". But maybe js-controls designed by another way...

**Comment by kaganer** [comment]
Maybe, if set in awesomplete.css
div.awesomplete > ul > li {
    width: 98%;
}

(with "overflow-x: hidden;") then may be some hack, temporary...
